spring:
  application:
    name: LibraryManagementSystem
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: dbuser
    password: 1234
    jpa.hibernate.ddl-auto: create #TODO : db 변경 후 None으로 수정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# swagger 설정
springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html